w4d6/AuthVideoDemo/config/routes.rb
AuthDemo::Application.routes.draw do
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resource :session, only: [:create, :destroy, :new]
  resource :user, only: [:create, :new, :show] do
    resource :counter, only: [:update]
  end
end

w4d6/AuthVideoDemo/app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    # no user with given username
    return nil if user.nil?

    # check user's password
    user.password_digest.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def password_digest
    BCrypt::Password.new(super)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end
end

w4d6/AuthVideoDemo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    # fetches the user we've logged in as
    return nil if self.session[:session_token].nil?
    @user ||= User.find_by(session_token: self.session[:session_token])
  end

  def log_in!(user)
    # force other clients to log out by regenerating token
    user.reset_session_token!
    # log this client in
    self.session[:session_token] = user.session_token
  end

  def log_out!
    self.session[:session_token] = nil
  end
end

w4d6/AuthVideoDemo/app/controllers/counters_controller.rb
class CountersController < ApplicationController
  def update
    current_user.counter = params[:user][:counter]
    current_user.save!
    redirect_to user_url
  end
end

w4d6/AuthVideoDemo/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # signs a user in
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user.nil?
      # no user with the given name!
      render :new
    else
      # sign the user in
      log_in!(@user)
      redirect_to user_url
    end
  end

  def destroy
    # sign a user out
    log_out!
    redirect_to new_session_url
  end

  def new
    # presents a login form
    render :new
  end
end

w4d6/AuthVideoDemo/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

w4d6/AuthVideoDemo/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    # sign up the user
    @user = User.new(user_params)
    if @user.save
      # redirect them to the new user's show page
      log_in!(@user)
      redirect_to user_url
    else
      # input didn't pass validation; re-render sign up form.
      render :new
    end
  end

  def new
    # present form for signup
    @user = User.new # dummy user object
    render :new
  end

  def show
    # show the user's details (just their username)
    if current_user.nil?
      # let them log in
      redirect_to new_session_url
      return
    end

    @user = current_user
    render :show
  end

  protected
  def user_params
    self.params.require(:user).permit(:username, :password)
  end
end

w4d6/AuthVideoDemo/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

w4d6/AuthVideoDemo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="navbar-header">

  </div>

  <div>
    <ul class="nav nav-pills">
      <li><a href="<%= new_session_url %>">Login</a></li>
      <li><a href="<%= new_user_url %>">Create User</a></li>
      <li><a href="<%= home_url %>">Home</a></li>
      <li><a href="<%= about_url %>">About</a></li>
      <li><a href="<%= contact_url %>">Contact</a></li>
    </ul>
  </div>
</nav>

<div class="container"><%= yield %></div>

</body>
</html>

w4d6/AuthVideoDemo/app/views/static_pages/about.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>This is a fantastic site. Wow.</h1>
    <div class="row">
      <div class="col-xs-6">
        <p>I mean just look at it. It's amazing.</p>
      </div>
      <div class="col-xs-6">
        <p>There are two whole columns here!</p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <h1 class="text-center">Meet the Team</h1>
  <p class="text-center">
    (of puppies!)
  </p>
</div>

<div class="row">
  <div class="col-xs-3">
    <img src="puppy1.jpg" alt="Puppy1" class="img-responsive img-circle center-block" />
    <h2 class="text-center">FuzzBall</h2>
    <%= render 'shared/lorem' %>
  </div>

  <div class="col-xs-3">
    <img src="puppy2.jpg" alt="Puppy2" class="img-responsive img-circle center-block" />
    <h2 class="text-center">Fido</h2>
    <%= render 'shared/lorem' %>
  </div>

  <div class="col-xs-3">
    <img src="puppy3.jpg" alt="Puppy3" class="img-responsive img-circle center-block" />
    <h2 class="text-center">Daisy</h2>
    <%= render 'shared/lorem' %>
  </div>

  <div class="col-xs-3">
    <img src="puppy4.jpg" alt="Puppy4" class="img-responsive img-circle center-block" />
    <h2 class="text-center">Sir Barkington</h2>
    <%= render 'shared/lorem' %>
  </div>
</div>

w4d6/AuthVideoDemo/app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<div class="row">
  <div class="col-xs-6">
    <form class="">
      <div class="form-group">
        <label for="test-field">Cool Text</label>
        <input type="text" class="form-control" name="name" value="">
      </div>

      <input type="button" class="btn btn-primary" value="Test Form">
    </form>
  </div>

  <div class="col-xs-6">
    <table class="table table-striped">
      <thead>
        <tr>
          <td>Name</td>
          <td>Phone Number</td>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>Alex Chebotarev</td>
          <td>(555)555-5555</td>
        </tr>

        <tr>
          <td>Some OtherGuy</td>
          <td>(555)555-5555</td>
        </tr>

        <tr>
          <td>AnAdditional Guy</td>
          <td>(555)555-5555</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

w4d6/AuthVideoDemo/app/views/static_pages/home.html.erb
<h1>Home</h1>