w4d4/music-app/config/routes.rb
MusicApp::Application.routes.draw do
  root 'bands#index'
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new]
end

w4d4/music-app/app/models/album.rb
class Album < ActiveRecord::Base
  PRODUCTION_TYPES = ["studio", "live"]

  validates :band_id, :name, presence: true
  validates :production, presence: true, inclusion: { in: PRODUCTION_TYPES }

  after_initialize :set_production

  belongs_to :band
  has_many :tracks, dependent: :destroy

  def set_production
    self.production ||= "studio"
  end
end

w4d4/music-app/app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums, dependent: :destroy
  has_many(
    :tracks,
    through: :albums,
    source: :tracks,
    dependent: :destroy
  )
end

w4d4/music-app/app/models/note.rb
class Note < ActiveRecord::Base
  validates :user_id, :track_id, presence: true
  validates :content, presence: true, blank: false

  belongs_to :user
  belongs_to :track
end

w4d4/music-app/app/models/track.rb
class Track < ActiveRecord::Base
  VARIETIES = ["regular", "bonus"]

  validates :album_id, :name, presence: true
  validates :variety, presence: true, inclusion: { in: VARIETIES }

  after_initialize :set_variety

  belongs_to :album

  has_many :notes
  
  has_one(
    :band,
    through: :album,
    source: :band
  )

  def set_variety
    self.variety ||= "regular"
  end
end

w4d4/music-app/app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :notes

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return nil unless user && user.is_password?(password)
    user
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    save!
    self.session_token
  end
end

w4d4/music-app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  helper_method :logged_in?
  helper_method :current_user

  before_action :verify_login

  def new
    @album = Album.new
    @bands = Band.all
  end

  def create
    @album = Album.new(album_params)
    @bands = Band.all

    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
    @album_tracks = @album.tracks
    @band = @album.band
  end

  def edit
    @album = Album.find(params[:id])
    @bands = Band.all
  end

  def update
    @album = Album.find(params[:id])
    @bands = Band.all
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.delete
    redirect_to bands_url
  end

  private

    def album_params
      params.require(:albums).permit(:band_id, :name, :production)
    end

    def verify_login
      redirect_to new_session_url unless logged_in?
    end
end

w4d4/music-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    login_user = User.find_by_credentials(user.email, params[:users][:password])
    session[:session_token] = login_user.reset_session_token!
  end

  def logout!(user)
    session[:session_token] = nil
    user.reset_session_token!
  end
end

w4d4/music-app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  helper_method :logged_in?
  helper_method :current_user

  before_action :verify_login

  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
    @band_albums = @band.albums
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.delete
    redirect_to bands_url
  end

  private

    def band_params
      params.require(:bands).permit(:name)
    end

    def verify_login
      redirect_to new_session_url unless logged_in?
    end
end

w4d4/music-app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  helper_method :current_user
  helper_method :logged_in?
  helper_method :logout!

  def new
    @user = User.new
  end

  def create
    email = params[:users][:email]
    password = params[:users][:password]
    @user = User.find_by_credentials(email, password)
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] << "Couldn't Login That User!"
      render :new
    end
  end

  def destroy
    logout!(current_user)
    redirect_to new_session_url
  end

  private

    def session_params
      params.require(:users).permit(:email, :password)
    end
end

w4d4/music-app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  helper_method :logged_in?
  helper_method :current_user

  before_action :verify_login

  def new
    @track = Track.new
    @albums = Album.all
  end

  def create
    @track = Track.new(track_params)
    @albums = Album.all

    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def show
    @track = Track.find(params[:id])
  end

  def edit
    @track = Track.find(params[:id])
    @albums = Album.all
  end

  def update
    @track = Track.find(params[:id])
    @albums = Album.all

    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.delete
    redirect_to bands_url
  end

  private

    def track_params
      params.require(:tracks).permit(:album_id, :name, :variety, :lyrics)
    end

    def verify_login
      redirect_to new_session_url unless logged_in?
    end
end

w4d4/music-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :current_user
  helper_method :logged_in?

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:users).permit(:email, :password)
    end
end

w4d4/music-app/app/helpers/albums_helper.rb
module AlbumsHelper
end

w4d4/music-app/app/helpers/bands_helper.rb
module BandsHelper
end

w4d4/music-app/app/helpers/tracks_helper.rb
module TracksHelper
end

w4d4/music-app/app/views/albums/_form.html.erb
<%= render 'shared/errors' %>

<form action="<%= form_action %>" method="post">
  <input type="hidden" name="_method" value="<%= form_method %>">

  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">

   <p>
     <label>Name
       <br /><input
              type="text"
              name="albums[name]"
              value="<%= album.name if album %>">
     </label>
   </p>

   <p>
     <label>Band
       <select name="albums[band_id]">
         <option value="">None</option>
         <% bands.each do |band| %>
            <option
              value="<%= band.id %>"
              <%= "selected" if current_band_id.to_i == band.id %>>
                <%= band.name %>
            </option>
         <% end %>
       </select>
     </label>
   </p>

   <p>
     <label>Produced:
       <br /><label>In Studio
         <input
           type="radio"
           name="albums[production]"
           value="studio"
           <%= "checked" if album.production == "studio" %>>
       </label>

       <br /><label>Live
         <input
           type="radio"
           name="albums[production]"
           value="live"
           <%= "checked" if album.production == "live" %>>
       </label>
     </label>
   </p>


  <input type="submit" value="<%= form_submit_text %>">
</form>

w4d4/music-app/app/views/albums/edit.html.erb
<h1>Edit Album</h1>
<%= render 'albums/form',
            form_submit_text: "Save Changes",
            form_action: album_url(@album),
            form_method: "patch",
            album: @album,
            bands: @bands,
            current_band_id: @album.id %>

w4d4/music-app/app/views/albums/new.html.erb
<h1>Create Album</h1>
<%= render 'albums/form',
            form_submit_text: "Create",
            form_action: albums_url,
            form_method: "post",
            album: @album,
            bands: @bands,
            current_band_id: params[:band_id] %>

w4d4/music-app/app/views/albums/show.html.erb
<h1>Album: <%= @album.name %></h1>
<h3>Production: <%= @album.production %></h3>
<% unless @album_tracks.empty? %>
  <ol>
    <% @album_tracks.each do |track| %>
      <li><%= link_to track.name, track_url(track) %></li>
    <% end %>
  </ol>
<% else %>
  <h2>No tracks!</h2>
<% end %>

<%= button_to "Create New Track",
            new_album_track_url(album_id: @album.id),
            method: :get %>
<%= button_to "Edit Album", edit_album_url(@album), method: :get %>
<%= button_to "Back to Band", band_url(@album.band_id), method: :get %>
<%= button_to "Create New Album",
            new_band_album_url(band_id: @album.band_id),
            method: :get %>

<%= button_to "Delete Album",
            album_url(@album),
            method: :delete,
            data: { confirm: "Really Delete #{@album.name}?" } %>

w4d4/music-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/header' %>

<%= yield %>

</body>
</html>

w4d4/music-app/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

w4d4/music-app/app/views/shared/_header.html.erb
<% if logged_in? %>
  <p>
    Logged In As <strong><%= current_user.email %></strong>
    <%= button_to "Logout", session_url, method: :delete %>
  </p>

<% else %>
  <p>
    <%= button_to "Log In", new_session_url, method: :get %>
    <%= button_to "Create User", new_user_url, method: :get %>
  </p>
<% end %>

w4d4/music-app/app/views/tracks/_form.html.erb
<%= render 'shared/errors' %>

<form action="<%= form_action %>" method="post">
  <input type="hidden" name="_method" value="<%= form_method %>">

  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">

   <p>
     <label>Name:
       <br /><input
              type="text"
              name="tracks[name]"
              value="<%= track.name if track %>">
     </label>
   </p>

   <p>
     <label>Album:
       <select name="tracks[album_id]">
         <option value="">None</option>
         <% albums.each do |album| %>
            <option
              value="<%= album.id %>"
              <%= "selected" if current_album_id.to_i == album.id %>>
                <%= album.name %>
            </option>
         <% end %>
       </select>
     </label>
   </p>

   <p>
     <label>Variety:
       <br /><label>Regular
         <input
           type="radio"
           name="tracks[variety]"
           value="regular"
           <%= "checked" if track.variety == "regular" %>>
       </label>

       <br /><label>Bonus
         <input
           type="radio"
           name="tracks[variety]"
           value="live"
           <%= "checked" if track.variety == "bonus" %>>
       </label>
     </label>
   </p>

   <p>
     <label for="tracks-lyrics">Lyrics:</label><br />

       <textarea
          id="track-lyrics"
          name="tracks[lyrics]"
          rows="20" cols="20"><%= track.lyrics %></textarea>
   </p>

  <input type="submit" value="<%= form_submit_text %>">
</form>

w4d4/music-app/app/views/tracks/edit.html.erb
<h1>Edit Track</h1>
<%= render 'tracks/form',
            form_submit_text: "Save Changes",
            form_action: track_url(@track),
            form_method: "patch",
            track: @track,
            albums: @albums,
            current_album_id: @track.album_id %>

w4d4/music-app/app/views/tracks/new.html.erb
<h1>Create Track</h1>
<%= render 'tracks/form',
            form_submit_text: "Create",
            form_action: tracks_url,
            form_method: "post",
            track: @track,
            albums: @albums,
            current_album_id: params[:album_id] %>

w4d4/music-app/app/views/tracks/show.html.erb
<h1>Track: <%= @track.name %></h1>
<h3>Variety: <%= @track.variety %></h3>
<% unless @track.lyrics.blank? %>
  <p><%= @track.lyrics %></p>
<% else %>
  <h2>No lyrics!</h2>
<% end %>

<%= button_to "Edit Track", edit_track_url(@track), method: :get %>
<%= button_to "Back to Album", album_url(@track.album_id), method: :get %>
<%= button_to "Create New Track",
            new_album_track_url(album_id: @track.album_id),
            method: :get %>

<%= button_to "Delete Track",
            track_url(@track),
            method: :delete,
            data: { confirm: "Really Delete #{@track.name}?" } %>