w4d2/ninety-nine-cats-app/config/routes.rb
Rails.application.routes.draw do
  root "cats#index"
  resources :cats do
    resources :cat_rental_requests, only: [:index]
  end

  resources :cat_rental_requests, except: [:index]
end

w4d2/ninety-nine-cats-app/app/models/cat.rb
class Cat < ActiveRecord::Base
  CAT_COLORS = ["white", "orange", "black", "calico"]

  has_many :cat_rental_requests, dependent: :destroy

  validates :birth_date, :name, :description, presence: true
  validates :sex, inclusion: { in: ["m", "f"] }, presence: true
  validates(
    :color,
    inclusion: { in: CAT_COLORS },
    presence: true
  )

  def self.colors
    CAT_COLORS
  end

  def age
    Time.now.year - birth_date.year
  end

end

w4d2/ninety-nine-cats-app/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  belongs_to :cat

  validates :cat_id, :start_date, :end_date, presence: true
  validates(
    :status, presence: true, inclusion: {in: %w[PENDING APPROVED DENIED]}
  )
  #validate :cat_chosen
  validate :no_overlapping_approved_requests

  after_initialize :set_status

  def cat_chosen
    if cat_id == 0
      errors.add(:cat_chosen, "Must choose cat")
    end
  end

  def overlapping_requests
    CatRentalRequest
    .where("cat_id = ? AND id != ? ", cat_id, id)
    .where(
      "(start_date BETWEEN :start_date AND :end_date) OR
      (end_date BETWEEN :start_date AND :end_date)",
      {start_date: start_date, end_date: end_date}
    )
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED' ")
  end

  def no_overlapping_approved_requests
    unless overlapping_approved_requests.empty? || self.status == "DENIED"
      errors.add(:overlap, "Cat already rented out during part of that period")
    end
  end

# protected
  def set_status
    self.status ||= "PENDING"
  end

  def approve!
    self.update!(status: "APPROVED")
    conflicts = overlapping_requests
    conflicts.each do |conflict|
      conflict.deny!
    end
  end

  def deny!
    self.update!(status: "DENIED")
  end

end

w4d2/ninety-nine-cats-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

w4d2/ninety-nine-cats-app/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    @cat = Cat.find(params[:cat_id])
    @requests = CatRentalRequest.where(cat_id: params[:cat_id])
  end

  def new
    @request = CatRentalRequest.new
    @cats = Cat.all
  end

  def create
    @cats = Cat.all
    @request = CatRentalRequest.new(cat_rental_request_params)
    if @request.save
      redirect_to cat_url(params[:cat_rental_request][:cat_id])
    else
      flash.now[:errors] = @request.errors.full_messages
      render :new
    end
  end


private
  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:start_date, :end_date, :cat_id)
  end
end

w4d2/ninety-nine-cats-app/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
    @requests = @cat.cat_rental_requests
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  private
    def cat_params
      params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
    end
end

w4d2/ninety-nine-cats-app/app/views/cats/_form.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <ul>
      <li> <%= error %> </li>
    </ul>
  <% end %>
<% end %>

<form action="<%= form_action %>" method="post">
  <input type="hidden" name="_method" value="<%= form_method  %>">
  <label for="cat-name">Name</label>
  <input type="text" name="cat[name]" value="<%= cat.name %>">

  <br /><br /><label for="cat-sex">Cat Gender
    <p>
      <input
        type="radio"
        name="cat[sex]"
        value="m"
        <%= "checked" if cat.sex == "m" %>
      >
        Male
    </p>
    <p>
      <input
        type="radio"
        name="cat[sex]"
        value="f"
        <%= "checked" if cat.sex == "f" %>
      >
        Female
    </p>
  </label>

  <label for="cat-birth-date">Birth Date</label>
  <input
    id="cat-birth-date"
    type="date"
    name="cat[birth_date]"
    value="<%= cat.birth_date %>">

  <p>
    <label for="cat-color">Color</label>
    <select name="cat[color]" id="cat-color">
      <option value="none" <%= 'selected' if cat.color.nil? %>>
        Choose Color
      </option>

      <% Cat.colors.each do |color| %>
        <option value="<%=color %>"<%= 'selected' if cat.color == color %> >
          <%= color.capitalize %>
        </option>
      <% end %>

    </select>
  </p>

  <p>
    <label for="cat-description">Describe your Cat</label>
    <br />
    <textarea
      name="cat[description]"
      id="cat-description"
      rows="5"
      cols="15"
      ><%= cat.description %></textarea>
  </p>

  <input type="submit" value="<%= button_name %>">

</form>

w4d2/ninety-nine-cats-app/app/views/cats/edit.html.erb
<h1>Fix that Cat right up!</h1>

<%= render "form",
  cat: @cat,
  form_method: 'patch',
  form_action: cat_url(@cat),
  button_name: 'FIX IT'
%>

w4d2/ninety-nine-cats-app/app/views/cats/index.html.erb
<h1>ALL THE CATS!</h1>

<% unless @cats.empty? %>
  <ul>
    <% @cats.each do |cat| %>
      <li>
        <%= link_to cat.name, cat_url(cat) %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= link_to "Create a new Cat", new_cat_url %>
<br /><%= link_to "Reserve a Cat!", new_cat_rental_request_url %>

w4d2/ninety-nine-cats-app/app/views/cats/new.html.erb
<h1>Bring your cat into the world!</h1>

<%= render "form",
  cat: @cat,
  form_method: 'post',
  form_action: cats_url,
  button_name: 'Create Cat'
%>

w4d2/ninety-nine-cats-app/app/views/cats/show.html.erb
<h1> <%= @cat.name %> </h1>

<ul>
   <li>Birth_date: <%= @cat.birth_date %>   </li>
   <li>Age: <%= @cat.age %>   </li>
   <li>Color: <%= @cat.color %></li>
   <li>Gender: <%= @cat.sex %></li>
   <li>Description: <%=@cat.description  %> </li>
</ul>

<%= link_to "Back to all cats", cats_url %>
<%= link_to "Edit this cat", edit_cat_url(@cat) %>

<h3> Rental requests for <%= @cat.name %></h3>

<% unless @requests.empty? %>
  <ul>
    <% @requests.sort { |x, y| x.start_date <=> y.start_date}.each do |request| %>
      <li>
        <p>Start Date: <%= request.start_date %></p>
        <p>End Date: <%= request.end_date %></p>
        <p>Status: <%= request.status %></p>
      </li><br />
    <% end %>
  </ul>
<% end %>